# Generated by Django 4.0.5 on 2024-09-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
