# Generated by Django 4.0.5 on 2024-09-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
