# Generated by Django 4.0.5 on 2024-09-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_libro_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
